#!/usr/bin/env python3
"""Generate the guest-side WALI host import shim (wali-imports.js) from the
Rust `libc` crate's WALI definitions.

WALI (WebAssembly Linux Interface) is the ABI Rust's wasm32-wali-linux-musl
target speaks: every Linux syscall is an individually-named wasm import
`wali.SYS_<name>(args...) -> i64`. This script reads the authoritative
signatures from the libc crate and emits a JS module that bridges each one to
the LinuxOnTab guest kernel's single `linux.syscall(nr, a0..a5)` dispatcher.

Usage:
    python3 gen-wali-imports.py [path-to-libc-wali-dir] > wali-imports.js
Default libc path is the one build-std downloaded under ~/.cargo/registry.
"""
import re, sys, glob, os

def find_libc_wali():
    pats = glob.glob(os.path.expanduser(
        "~/.cargo/registry/src/*/libc-0.2*/src/unix/linux_like/linux/musl/b64/wasm32"))
    if not pats:
        sys.exit("libc WALI dir not found; build-std once, or pass the path")
    return sorted(pats)[-1]

def main():
    W = sys.argv[1] if len(sys.argv) > 1 else find_libc_wali()
    mod = open(f"{W}/mod.rs").read()
    wali = open(f"{W}/wali.rs").read()

    # syscall name -> number (mod.rs consts)
    nums = {m.group(1): int(m.group(2))
            for m in re.finditer(r'pub const SYS_(\w+):\s*c_long\s*=\s*(\d+);', mod)}
    # per-syscall arg types (wali.rs extern imports)
    sigs = {}
    for m in re.finditer(r'pub fn __syscall_SYS_(\w+)\(([^)]*)\)\s*->\s*c_long;', wali, re.S):
        args = [a.split(':')[1].strip()
                for a in m.group(2).split(',') if a.strip()]
        sigs[m.group(1)] = args

    # WALI uses a couple of legacy names; map to the numbered const
    ALIAS = {"fstatat": "newfstatat", "fadvise": "fadvise64"}
    rows = []
    for name, args in sigs.items():
        key = ALIAS.get(name, name)
        if key not in nums:
            sys.stderr.write(f"skip (no number): SYS_{name}\n"); continue
        kinds = ''.join('l' if t in ('i64', 'u64') else 'i' for t in args)
        rows.append((name, nums[key], kinds))
    rows.sort(key=lambda r: r[1])

    out = sys.stdout
    out.write("// AUTO-GENERATED by toolchain/wali/gen-wali-imports.py — do not edit.\n")
    out.write("// WALI host import module bridging wali.SYS_* -> guest linux.syscall.\n")
    out.write("// See toolchain/wali/README.md. i64 boundary needs BigInt; 'l' args are\n")
    out.write("// 64-bit offsets — verify against a real wali-musl binary (TODO-OFFSET).\n\n")
    out.write("export function makeWaliImports({ syscall, getArgc, getArgLen, copyArg }) {\n")
    out.write("  const B = BigInt;\n")
    out.write("  const n = (x) => (typeof x === 'bigint' ? Number(x) : x);\n")
    out.write("  const wali = {\n")
    out.write("    __cl_get_argc: () => getArgc() >>> 0,\n")
    out.write("    __cl_get_argv_len: (i) => getArgLen(n(i)) >>> 0,\n")
    out.write("    __cl_copy_argv: (buf, i) => { copyArg(n(buf), n(i)); return 0; },\n")
    for name, nr, kinds in rows:
        p = [chr(ord('a') + i) for i in range(len(kinds))]
        call = ", ".join(f"n({x})" for x in p)
        todo = "  /* TODO-OFFSET */" if 'l' in kinds else ""
        out.write(f"    SYS_{name}: ({', '.join(p)}) => B(syscall({nr}, {call})),{todo}\n")
    out.write("  };\n")
    out.write("  const envExtra = {\n")
    out.write("    _Unwind_Backtrace: () => 0, _Unwind_GetIP: () => 0, _Unwind_GetIPInfo: () => 0,\n")
    out.write("  };\n")
    out.write("  return { wali, envExtra };\n}\n")
    sys.stderr.write(f"generated {len(rows)} syscalls "
                     f"({sum(1 for _,_,k in rows if 'l' in k)} with 64-bit args)\n")

if __name__ == "__main__":
    main()
