#!/bin/sh
# Generate the gcc3_wasm bridge's RTTI lookup table for Linux on wasm32.
# The Emscripten build finds exception type_info objects by name through
# JavaScript (EM_JS jsGetExportedSymbol over the module's exports); a plain
# wasm module has no such lookup, so map the names wasmbridgegen lists in its
# "exports" file to weak references to the symbols. The file uses Emscripten's
# export spelling (an extra leading underscore: __ZTI...); the symbols and the
# names the bridge looks up are _ZTI.... A type whose RTTI is not
# linked in resolves to null, and the bridge then synthesizes one, exactly as
# when the Emscripten lookup misses.
#   sh make-rtti-table.sh <exports> > rtti-table.cxx
set -eu
echo '// generated by bridges/source/cpp_uno/gcc3_wasm/make-rtti-table.sh -- do not edit'
echo '#include <cstring>'
while read -r s; do
  [ -n "$s" ] && echo "extern \"C\" __attribute__((weak)) char const ${s#_}[];"
done < "$1"
echo 'namespace { struct Entry { char const* name; void const* rtti; };'
echo 'Entry const table[] = {'
while read -r s; do
  [ -n "$s" ] && echo "    { \"${s#_}\", ${s#_} },"
done < "$1"
echo '    { nullptr, nullptr } }; }'
echo 'extern "C" void* lo_wasm_getExportedSymbol(char const* name) {'
echo '    for (Entry const* e = table; e->name != nullptr; ++e)'
echo '        if (std::strcmp(e->name, name) == 0) return const_cast<void*>(e->rtti);'
echo '    return nullptr; }'
