#!/usr/bin/env python3
"""Generate librfb_font.h: the anti-aliased UI font for librfb's chrome
(window titles, taskbar labels, clock).

Glyphs are rendered once on the host with FreeType (via Pillow) into 8-bit
coverage masks, so the guest needs no font engine: librfb blends each mask
over whatever the framebuffer already holds.

    python3 tools/gen-ui-font.py /path/to/Inter-Medium.ttf 13 > librfb_font.h

Inter is SIL OFL 1.1 (https://github.com/rsms/inter) — embedding glyph
bitmaps in a program is permitted; the notice travels in the header.
"""
import sys
from PIL import Image, ImageDraw, ImageFont

path = sys.argv[1]
size = int(sys.argv[2]) if len(sys.argv) > 2 else 13
font = ImageFont.truetype(path, size)
ascent, descent = font.getmetrics()

glyphs, data = [], []
OX, OY = size, 2 * size                             # pen origin on the scratch canvas
for code in range(32, 127):
    ch = chr(code)
    adv16 = round(font.getlength(ch) * 16)          # 1/16 px, for fractional pen
    # Draw at a known baseline origin and crop to the real ink, so offsets
    # are exact (getmask pads to the line box: '"' came out 11 px tall).
    img = Image.new("L", (4 * size, 3 * size), 0)
    ImageDraw.Draw(img).text((OX, OY), ch, font=font, fill=255, anchor="ls")
    box = img.getbbox()
    off = len(data)
    if not box:
        glyphs.append((adv16, 0, 0, 0, 0, off))
        continue
    x0, y0, x1, y1 = box
    for yy in range(y0, y1):
        for xx in range(x0, x1):
            data.append(img.getpixel((xx, yy)))
    glyphs.append((adv16, x0 - OX, y0 - OY, x1 - x0, y1 - y0, off))

print(f"""/* librfb_font.h — GENERATED by tools/gen-ui-font.py; do not edit.
 *
 * {font.getname()[0]} {font.getname()[1]}, {size} px, ASCII 32..126, 8-bit coverage.
 * Copyright (c) 2016 The Inter Project Authors (https://github.com/rsms/inter)
 * Licensed under the SIL Open Font License, Version 1.1 (http://scripts.sil.org/OFL).
 */
#ifndef LIBRFB_FONT_H
#define LIBRFB_FONT_H
#include <stdint.h>

#define UIF_ASCENT  {ascent}
#define UIF_DESCENT {descent}
#define UIF_FIRST   32
#define UIF_LAST    126

/* adv16 = advance in 1/16 px; x,y = bitmap offset from the pen on the
 * baseline (y < 0 is above it); w,h = bitmap size; off = index into UIF_BITS */
static const struct {{ uint16_t adv16; int8_t x, y; uint8_t w, h; uint16_t off; }}
UIF_GLYPHS[{len(glyphs)}] = {{""")
for i, (adv16, x0, y0, w, h, off) in enumerate(glyphs):
    print(f"    {{{adv16},{x0},{y0},{w},{h},{off}}},  /* {chr(32 + i)!r} */")
print("};\n")
print(f"static const uint8_t UIF_BITS[{max(1, len(data))}] = {{")
for i in range(0, len(data), 24):
    print("    " + ",".join(str(v) for v in data[i:i + 24]) + ",")
print("};\n#endif")
