/* ffi.h — the slice of libffi that GLib needs, for wasm32 (LinuxOnTab).
 *
 * libffi has no wasm32 port outside emscripten (whose ffi_call goes through
 * JavaScript). GObject only calls ffi_prep_cif + ffi_call (the generic signal
 * marshaller); a wasm call_indirect must use the callee's exact signature,
 * so ffi_call classifies every argument as i32/i64/f32/f64 and dispatches to
 * a cast with that signature (ffi_dispatch.c, generated by gen-dispatch.py).
 * Closures (girepository) are not supported: ffi_closure_alloc returns NULL.
 */
#ifndef LOT_FFI_H
#define LOT_FFI_H
#include <stddef.h>
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif

#define FFI_TYPE_VOID       0
#define FFI_TYPE_INT        1
#define FFI_TYPE_FLOAT      2
#define FFI_TYPE_DOUBLE     3
#define FFI_TYPE_LONGDOUBLE 4
#define FFI_TYPE_UINT8      5
#define FFI_TYPE_SINT8      6
#define FFI_TYPE_UINT16     7
#define FFI_TYPE_SINT16     8
#define FFI_TYPE_UINT32     9
#define FFI_TYPE_SINT32     10
#define FFI_TYPE_UINT64     11
#define FFI_TYPE_SINT64     12
#define FFI_TYPE_STRUCT     13
#define FFI_TYPE_POINTER    14
#define FFI_TYPE_COMPLEX    15
#define FFI_TYPE_LAST       FFI_TYPE_COMPLEX

typedef struct _ffi_type {
  size_t size;
  unsigned short alignment;
  unsigned short type;
  struct _ffi_type **elements;
} ffi_type;

typedef enum { FFI_OK = 0, FFI_BAD_TYPEDEF, FFI_BAD_ABI, FFI_BAD_ARGTYPE } ffi_status;
typedef enum { FFI_FIRST_ABI = 0, FFI_WASM32, FFI_LAST_ABI, FFI_DEFAULT_ABI = FFI_WASM32 } ffi_abi;

typedef unsigned long ffi_arg;
typedef signed long ffi_sarg;

typedef struct {
  ffi_abi abi;
  unsigned nargs;
  ffi_type **arg_types;
  ffi_type *rtype;
  unsigned bytes;
  unsigned flags;
} ffi_cif;

extern ffi_type ffi_type_void, ffi_type_uint8, ffi_type_sint8, ffi_type_uint16,
    ffi_type_sint16, ffi_type_uint32, ffi_type_sint32, ffi_type_uint64,
    ffi_type_sint64, ffi_type_float, ffi_type_double, ffi_type_longdouble,
    ffi_type_pointer;

#define ffi_type_uchar  ffi_type_uint8
#define ffi_type_schar  ffi_type_sint8
#define ffi_type_ushort ffi_type_uint16
#define ffi_type_sshort ffi_type_sint16
#define ffi_type_uint   ffi_type_uint32
#define ffi_type_sint   ffi_type_sint32
#define ffi_type_ulong  ffi_type_uint32
#define ffi_type_slong  ffi_type_sint32

ffi_status ffi_prep_cif(ffi_cif *cif, ffi_abi abi, unsigned int nargs,
                        ffi_type *rtype, ffi_type **atypes);
ffi_status ffi_prep_cif_var(ffi_cif *cif, ffi_abi abi, unsigned int nfixedargs,
                            unsigned int ntotalargs, ffi_type *rtype,
                            ffi_type **atypes);
void ffi_call(ffi_cif *cif, void (*fn)(void), void *rvalue, void **avalue);

/* closures: not available on this target */
#define FFI_CLOSURES 0
typedef struct { ffi_cif *cif; void (*fun)(ffi_cif *, void *, void **, void *); void *user_data; } ffi_closure;
void *ffi_closure_alloc(size_t size, void **code);
void ffi_closure_free(void *closure);
ffi_status ffi_prep_closure_loc(ffi_closure *closure, ffi_cif *cif,
                                void (*fun)(ffi_cif *, void *, void **, void *),
                                void *user_data, void *codeloc);

#define FFI_FN(f) ((void (*)(void))(f))

#ifdef __cplusplus
}
#endif
#endif
