#!/usr/bin/env python3
"""Generate ffi_wasm.c: libffi's ffi_prep_cif/ffi_call for wasm32 (see ffi.h).

A wasm call_indirect must match the callee's exact signature, so ffi_call
classifies each argument as I (i32: ints up to 32 bits, pointers), J (i64),
F (f32) or D (f64), packs the classes and the return class into a key and
switches to a cast with that signature. Covered: every class mix up to 4
arguments, I/D mixes for 5-6 arguments, all-I up to 12 arguments (GObject
signal handlers: instance, a few args, user data). Anything else aborts
with the signature, so a missing shape is obvious rather than a trap.

    python3 gen-dispatch.py > ffi_wasm.c
"""
import itertools

CT = {"I": "int32_t", "J": "int64_t", "F": "float", "D": "double"}
SLOT = {"I": "i", "J": "j", "F": "f", "D": "d"}
RET = {"V": 1, "I": 2, "J": 3, "F": 4, "D": 5}
ARG = {"I": 1, "J": 2, "F": 3, "D": 4}


def key(ret, args):
    k = RET[ret]
    for a in args:
        k = k * 5 + ARG[a]
    return k


def shapes():
    for n in range(0, 5):
        yield from itertools.product("IJFD", repeat=n)
    for n in (5, 6):
        yield from itertools.product("ID", repeat=n)
    for n in range(7, 13):
        yield ("I",) * n


out = []
w = out.append
w("/* generated by gen-dispatch.py — do not edit */")
w("#include <stdint.h>")
w("#include <stdio.h>")
w("#include <stdlib.h>")
w("#include <string.h>")
w('#include "ffi.h"')
w("")
w("#define T(n, ty, sz, al) ffi_type ffi_type_##n = { sz, al, ty, 0 };")
w("T(void, FFI_TYPE_VOID, 1, 1)")
w("T(uint8, FFI_TYPE_UINT8, 1, 1) T(sint8, FFI_TYPE_SINT8, 1, 1)")
w("T(uint16, FFI_TYPE_UINT16, 2, 2) T(sint16, FFI_TYPE_SINT16, 2, 2)")
w("T(uint32, FFI_TYPE_UINT32, 4, 4) T(sint32, FFI_TYPE_SINT32, 4, 4)")
w("T(uint64, FFI_TYPE_UINT64, 8, 8) T(sint64, FFI_TYPE_SINT64, 8, 8)")
w("T(float, FFI_TYPE_FLOAT, 4, 4) T(double, FFI_TYPE_DOUBLE, 8, 8)")
w("T(longdouble, FFI_TYPE_LONGDOUBLE, 16, 16) T(pointer, FFI_TYPE_POINTER, 4, 4)")
w("")
w("""static int cls(const ffi_type *t) {
  switch (t->type) {
  case FFI_TYPE_VOID: return 'V';
  case FFI_TYPE_INT: case FFI_TYPE_UINT8: case FFI_TYPE_SINT8:
  case FFI_TYPE_UINT16: case FFI_TYPE_SINT16: case FFI_TYPE_UINT32:
  case FFI_TYPE_SINT32: case FFI_TYPE_POINTER: return 'I';
  case FFI_TYPE_UINT64: case FFI_TYPE_SINT64: return 'J';
  case FFI_TYPE_FLOAT: return 'F';
  case FFI_TYPE_DOUBLE: return 'D';
  default: return 0;   /* structs, long double: unsupported */
  }
}

ffi_status ffi_prep_cif(ffi_cif *cif, ffi_abi abi, unsigned int nargs,
                        ffi_type *rtype, ffi_type **atypes) {
  if (abi != FFI_DEFAULT_ABI) return FFI_BAD_ABI;
  if (!cls(rtype)) return FFI_BAD_TYPEDEF;
  for (unsigned i = 0; i < nargs; i++)
    if (!cls(atypes[i]) || cls(atypes[i]) == 'V') return FFI_BAD_ARGTYPE;
  cif->abi = abi; cif->nargs = nargs; cif->arg_types = atypes;
  cif->rtype = rtype; cif->bytes = 0; cif->flags = 0;
  return FFI_OK;
}

ffi_status ffi_prep_cif_var(ffi_cif *cif, ffi_abi abi, unsigned int nfixed,
                            unsigned int ntotal, ffi_type *rtype, ffi_type **atypes) {
  (void)nfixed;   /* wasm32 varargs go through memory: not callable this way */
  return ffi_prep_cif(cif, abi, ntotal, rtype, atypes);
}

void *ffi_closure_alloc(size_t size, void **code) { (void)size; if (code) *code = 0; return 0; }
void ffi_closure_free(void *c) { (void)c; }
ffi_status ffi_prep_closure_loc(ffi_closure *c, ffi_cif *cif,
    void (*fun)(ffi_cif *, void *, void **, void *), void *ud, void *codeloc) {
  (void)c; (void)cif; (void)fun; (void)ud; (void)codeloc;
  return FFI_BAD_ABI;
}

typedef union { int32_t i; int64_t j; float f; double d; } slot;

static void load(slot *s, const ffi_type *t, const void *p) {
  switch (t->type) {
  case FFI_TYPE_UINT8:  s->i = *(const uint8_t *)p; break;
  case FFI_TYPE_SINT8:  s->i = *(const int8_t *)p; break;
  case FFI_TYPE_UINT16: s->i = *(const uint16_t *)p; break;
  case FFI_TYPE_SINT16: s->i = *(const int16_t *)p; break;
  case FFI_TYPE_UINT64: case FFI_TYPE_SINT64: memcpy(&s->j, p, 8); break;
  case FFI_TYPE_FLOAT:  memcpy(&s->f, p, 4); break;
  case FFI_TYPE_DOUBLE: memcpy(&s->d, p, 8); break;
  default:              memcpy(&s->i, p, 4); break;
  }
}

void ffi_call(ffi_cif *cif, void (*fn)(void), void *rvalue, void **avalue) {
  slot s[12], r;
  char sig[16];
  unsigned n = cif->nargs;
  int rc = cls(cif->rtype);
  uint64_t key = rc == 'V' ? 1 : rc == 'I' ? 2 : rc == 'J' ? 3 : rc == 'F' ? 4 : 5;
  memset(&r, 0, sizeof r);
  if (n > 12) goto missing;
  for (unsigned k = 0; k < n; k++) {
    int c = cls(cif->arg_types[k]);
    key = key * 5 + (c == 'I' ? 1 : c == 'J' ? 2 : c == 'F' ? 3 : 4);
    load(&s[k], cif->arg_types[k], avalue[k]);
  }
  switch (key) {""")
for args in shapes():
    for ret in "VIJFD":
        params = ", ".join(CT[a] for a in args) or "void"
        call = ", ".join("s[%d].%s" % (i, SLOT[a]) for i, a in enumerate(args))
        rt = "void" if ret == "V" else CT[ret]
        expr = "((%s (*)(%s))fn)(%s)" % (rt, params, call)
        stmt = expr + ";" if ret == "V" else "r.%s = %s;" % (SLOT[ret], expr)
        w("  case %dULL: %s break;" % (key(ret, args), stmt))
w("""  default: goto missing;
  }
  if (rvalue) {
    switch (rc) {
    case 'I': {   /* integral results smaller than ffi_arg widen to it */
      ffi_arg v;
      switch (cif->rtype->type) {
      case FFI_TYPE_SINT8: case FFI_TYPE_SINT16: case FFI_TYPE_SINT32: case FFI_TYPE_INT:
        v = (ffi_arg)(ffi_sarg)r.i; break;
      case FFI_TYPE_UINT8:  v = (uint8_t)r.i; break;
      case FFI_TYPE_UINT16: v = (uint16_t)r.i; break;
      default:              v = (ffi_arg)(uint32_t)r.i; break;
      }
      memcpy(rvalue, &v, sizeof v); break;
    }
    case 'J': memcpy(rvalue, &r.j, 8); break;
    case 'F': memcpy(rvalue, &r.f, 4); break;
    case 'D': memcpy(rvalue, &r.d, 8); break;
    }
  }
  return;
missing:
  sig[0] = (char)rc; sig[1] = '(';
  {
    unsigned k = 0;
    for (; k < n && k < 12; k++) sig[2 + k] = (char)cls(cif->arg_types[k]);
    sig[2 + k] = ')'; sig[3 + k] = 0;
  }
  fprintf(stderr, "libffi (wasm32): no dispatch for signature %s\\n", sig);
  abort();
}""")
print("\n".join(out))
