#!/bin/sh
# C++ compiler wrapper for the wasm32-wali-linux-musl target: clang 22 + wali-musl + the WALI libc++ (/tmp/wali-libcxx)
exec /tmp/llvm22/bin/clang++ --target=wasm32-unknown-linux-muslwali --sysroot=/tmp/wali-sysroot -O2 -pthread -fdeclspec -fwasm-exceptions -mcpu=generic -matomics -mbulk-memory -mexception-handling -stdlib=libc++ -nostdinc++ -isystem /tmp/wali-libcxx/include/c++/v1 -Wno-user-defined-literals -Wno-nullability-completeness "$@"
