set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR wasm32)
set(CMAKE_CROSSCOMPILING ON)
set(CMAKE_C_COMPILER   /tmp/wali-tools/wali-cc)
set(CMAKE_CXX_COMPILER /tmp/wali-tools/wali-c++)
set(CMAKE_ASM_COMPILER /tmp/wali-tools/wali-cc)
set(CMAKE_C_COMPILER_WORKS ON)
set(CMAKE_CXX_COMPILER_WORKS ON)
set(CMAKE_C_COMPILER_FORCED ON)
set(CMAKE_CXX_COMPILER_FORCED ON)
set(CMAKE_SYSROOT /tmp/wali-sysroot)
set(CMAKE_AR     /tmp/llvm22/bin/llvm-ar)
set(CMAKE_RANLIB /tmp/llvm22/bin/llvm-ranlib)
set(CMAKE_NM     /tmp/llvm22/bin/llvm-nm)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld -nostartfiles /tmp/wali-sysroot/lib/crt1.o -L/tmp/wali-sysroot/lib -L/tmp/wali-libcxx/lib -Wl,--import-memory -Wl,--export-memory -Wl,--shared-memory -Wl,--max-memory=4294967296")
set(CMAKE_CXX_STANDARD_LIBRARIES "/tmp/wali-libcxx/lib/libc++.a /tmp/wali-libcxx/lib/libc++abi.a /tmp/wali-libcxx/lib/libunwind.a")
